### ISSUE TITLE
Improve component registration

### ISSUE THREAD

**Issue by freekmurze** [spatie/laravel-blade-x#32]
It should be possible to do this:

```
BladeX::component('admin.components.text-field');
BladeX::component('admin.components.*');
BladeX::component('bladex::components.text-field');
BladeX::component('bladex::components.*');
```

**Comment by freekmurze** [comment]
It should be possible to do this:

```
BladeX::component('admin.components.text-field');
BladeX::component('admin.components.*');
BladeX::component('bladex::components.text-field');
BladeX::component('bladex::components.*');
```

**Comment by jstoone** [comment]
I've had a really good stab at this yesterday, and very close to be finished. I just need to clean up a bit and then I have PR ready solving this issue.

**Comment by freekmurze** [comment]
Thanks for you efforts around this, meanwhile I've already implemented in myself in the `v2` which we are going to release soon. If you have any improvements, please send a PR to the `v2` branch.

**Comment by freekmurze** [comment]
Implemented in `v2`.

**Comment by jstoone** [comment]
Oh man, totally overlooked that it first of all already was assigned to you, and secondly that there was a `v2`-branch.

Just had a look, and I had the exact same approach, although I removed the ability to register components from a absolute-path directory. Mainly because currently (in  `master`) the user is only able to require component directories using an absolute path, which does not fit with the `README`.

**Example:**
```php
// Absolute: Works
BladeX::components(__DIR__.'/subs/components');

// Relative: Fails
BladeX::components('components');
```

**Summa summarum**
- I'll save my branch with a patch for the above, in case you want to maintain `v1`. 
- A few refactors of mine might still apply to `v2` so I'll have a stab at it.

**Comment by freekmurze** [comment]
> I'll save my branch with a patch for the above, in case you want to maintain v1.
We're not going to maintain `v1`, we'll advise everybody to migrate to v2. I've added an `UPGRADING.md` with instructions.

> BladeX::components(__DIR__.'/subs/components');
We are not going to support this anymore, we'll only have support for relative paths.

The docs for `v2` will be here: https://docs.spatie.be/laravel-blade-x/v2/introduction
