### ISSUE TITLE
How to use BladeX outside of Laravel

### ISSUE THREAD

**Issue by zacksmash** [spatie/laravel-blade-x#57]
First off, I'm excited to use this package on pretty much every Laravel project, moving forward!

However, I also would like to use this in a Wordpress site. I'm using a fork of the latest Sage/Roots theme, which incorporates Blade into the Wordpress template files. It also includes a package to give you "Controllers", which gives Wordpress a more MVC feel. 

I've tried to register this package multiple ways within the theme, but I keep getting a few errors that I don't know how to resolve.

First: Is it even possible to use this package without Laravel?

Second: Here's a couple of the errors I get:

```
$bladex = \Spatie\BladeX\BladeX();

$bladex->component('components.*');
```
`Fatal error: Uncaught RuntimeException: A facade root has not been set.`

And

```
use Spatie\BladeX\BladeX;

BladeX::component('components.*');
```

`Fatal error: Uncaught Error: Using $this when not in object context in`

Any help would be greatly appreciated!

**Comment by freekmurze** [comment]
This package is very much tied to Laravel. In order to use it outside of Laravel you'll have to get Blade running in your project. I know Matt Stauffer had a project with examples on how to extract components: https://github.com/mattstauffer/Torch

But even with Blade running you'll still have some work translating service provider and some ioc binding to your project. I think it's doable, but it won't be fun 😄 

We are not going to invest anytime in this as we don't need Blade X outside of Laravel.

Good luck! And feel free to fork our code to create a version that is not dependant on Laravel.
